### ISSUE TITLE
Workplan

### ISSUE THREAD

**Issue by BoxedSnake** [Scrin445/SenseHAT-Man#1]
William: 5 SenseHAT-Man , 7 ghost: scaredy ghost ,8 dying SenseHAT-Man
Dylan: 1 Pinky ,2 Inky ,3 Clyde

**Comment by BoxedSnake** [comment]
finished 7. Scaredy

**Comment by Scrin445** [comment]
Clyde branch made and code successfully pushed.

Also, post updates on your repo, not mine.

**Comment by BoxedSnake** [comment]
okay

**Comment by Scrin445** [comment]
Late one here; Inky and Pinky ghost code successfully made and merged to master. Main code has also been updated.

In other words, I've finished my half.
